### ISSUE TITLE
How to get deeper relation results

### ISSUE THREAD

**Issue by rickerd** [alantiller/directus-php-sdk#12]
In the API it's possible to get deeper relational items.
Is this also possible in the SDK?
If not, I would like to implement is myself. I just don't know where to look.

I thought it was somewhere in the function "make_call()".

**Comment by alantiller** [comment]
Hi @rickerd,

Could you give me some context on what you mean by deeper relational items? If you can give me an example I can have a look. The private function make_call() is the curl function used to make all API calls although I'm about to rejig the code to add some new features so bear with on that.

Regards,

Alan,

**Comment by rickerd** [comment]
I meant to get deeper results from a relation.
But I think I got it covered with the get() function.

```
   $this->directus->get('/items/hero/', [
      'search' => 'default',
      'fields' => ['*,image.*,image.hero_image_id.*,image.hero_image_id.image.*'],
   ])
```

**Comment by rickerd** [comment]
Nah it works now!
And it didn't took that long ;) no worries.
Your library works perfect!!

Thank you very much Alan.
