### ISSUE TITLE
php8 support for composer

### ISSUE THREAD

**Issue by torstenhoegel** [alantiller/directus-php-sdk#18]
I am sadly unable to easily install your php-sdk with php8 (8.0.18) in my current project.

```
Package alantiller/directus-php-sdk has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - alantiller/directus-php-sdk v1.0.2 requires php ^7.0 which does not match your installed version 8.0.18.
```

I have not been seeing any issues yet using the current version with PHP 8, therefore this should be an easy fix.

Thanks in advance!

**Comment by andrii-bodnar** [comment]
Hi @torstenhoegel, it's already done - #14 

all we need now is to release a new version of the package.

cc @alantiller

**Comment by alantiller** [comment]
Soooorrrry, completely forgot. Done it this time haha

**Comment by torstenhoegel** [comment]
thanks guys 👍🏻

**Comment by ricardovigatti** [comment]
Is this package compatible with PHP 8.3 and 8.4?
