### ISSUE TITLE
Errors Int(35)

### ISSUE THREAD

**Issue by EmmanuelMK1234** [alantiller/directus-php-sdk#20]
Bonjour tous le monde
J'obtiens cette erreur lorsque je lance la requête avec le sdk de directus
array(1) { ["errors"]=> int(35) }
Pourriez-vous m'aider a résoudre cette erreur

**Comment by EmmanuelMK1234** [comment]
It's already resolved, thanks 
So how Can i see the log off sdk in use ??

**Comment by EmmanuelMK1234** [comment]
the log of*

**Comment by nervusdm** [comment]
> Bonjour tous le monde J'obtiens cette erreur lorsque je lance la requête avec le sdk de directus array(1) { ["errors"]=> int(35) } Pourriez-vous m'aider a résoudre cette erreur

Quel était le probleme ? Je m'arrache les cheveux avec cela. Alors que je l'ai déjà utilisé ailleurs sans probleme.

**Comment by nervusdm** [comment]
Ok, c'était l'url.

Bad url in the configuration.

**Comment by alantiller** [comment]
There is not great logging in V1 of the Directus SDK. I'm still working on V2 which brings it into alignment with the JS SDK and also includes logging. I tend to check the Apache/PHP error log if I need to work out what the problem might be.

**Comment by alantiller** [comment]
Your more than welcome to try V2 but it is still in a untested state and authentication is still a problem.

https://github.com/alantiller/directus-php-sdk/tree/feat-v2

**Comment by nervusdm** [comment]
It's ok @alantiller   you are doing an awesome job. Thanks
